###

POST http:/localhost:3000/api/moro
content-type: application/json;

{
    "sender": "Atte",
    "message": "testitervehdys"
}

### get new
POST http:/localhost:3000/api/items
### post new
POST http:/localhost:3000/api/items
content-type: application/json;

{
    "name": "Sitruuna"
}
